# Generated by Django 4.2.5 on 2023-10-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_alter_autopartscategory_parent_alter_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoparts',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
