# Generated by Django 4.2.5 on 2023-12-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_autoparts_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoparts',
            name='name',
            field=models.CharField(default='шины', max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
