# Generated by Django 4.2.5 on 2024-01-08 09:50

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('parts', '0006_autoparts_name_en_autoparts_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopartscategory',
            name='characteristics',
            field=taggit.managers.TaggableManager(blank=True, help_text='Введите характеристики через запятую(Например, если это шина, то радиус, ширина, высота. Если это двигатель, то объем, мощность, тип. )', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Характеристики'),
        ),
    ]
