# Generated by Django 4.2.5 on 2023-10-03 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=50, verbose_name='Имя продавца')),
                ('customer_name', models.CharField(max_length=50, verbose_name='Имя покупателя')),
                ('unread_messages_count', models.PositiveSmallIntegerField(default=0, verbose_name='Количество непрочитанных сообщений')),
                ('last_message_received_time', models.DateTimeField(verbose_name='Время последнего сообщения')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('content', models.TextField(verbose_name='Cообщение')),
                ('attachment', models.FileField(blank=True, upload_to='attachments/', verbose_name='Вложение')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communication.chat', verbose_name='Чат')),
            ],
        ),
    ]
