# Generated by Django 4.2.5 on 2023-10-24 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_remove_chat_id_alter_chat_temp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='temp_id',
            new_name='id',
        ),
    ]
