# Generated by Django 4.2.5 on 2023-10-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0007_alter_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='last_message_received_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего сообщения'),
        ),
    ]
