# Generated by Django 4.2.5 on 2023-10-29 20:56

import apps.communication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0011_chat_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='attachment',
            field=models.FileField(blank=True, upload_to=apps.communication.models.get_upload_path, verbose_name='Вложение'),
        ),
    ]
