# Generated by Django 4.2.5 on 2024-02-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0012_alter_messages_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Cообщение'),
        ),
    ]
