# Generated by Django 4.2.5 on 2023-10-07 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterskill',
            options={'verbose_name': 'Специализация мастера', 'verbose_name_plural': 'Специализации мастеров'},
        ),
    ]
