# Generated by Django 4.2.5 on 2023-10-08 05:04

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_masterskill_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='masterskill',
            name='level',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterskill',
            name='lft',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterskill',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Родительская специализация мастера', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='users.masterskill', verbose_name='Родительская специализация'),
        ),
        migrations.AddField(
            model_name='masterskill',
            name='rght',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterskill',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='masterskill',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='region',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Регион, в котором находится район', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='users.region', verbose_name='Регион'),
        ),
    ]
