# Generated by Django 4.2.5 on 2023-10-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_options_masterskill_level_masterskill_lft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='company_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефона компании'),
        ),
    ]
