# Generated by Django 4.2.5 on 2023-10-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AlterField(
            model_name='master',
            name='skilled_at',
            field=models.ManyToManyField(blank=True, related_name='masters', to='users.masterskill', verbose_name='Специализация мастера'),
        ),
    ]
