# Generated by Django 4.2.5 on 2023-12-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_region_options_alter_master_skilled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт'),
        ),
    ]
