# Generated by Django 4.2.5 on 2023-12-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_sellerimage'),
        ('users', '0009_master_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='seller_images',
            field=models.ManyToManyField(blank=True, related_name='sellers', to='images.sellerimage'),
        ),
    ]
