# Generated by Django 4.2.5 on 2024-01-03 16:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_master_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Местоположение'),
        ),
    ]
