# Generated by Django 4.2.5 on 2024-02-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_master_start_of_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='start_of_carrier',
            field=models.PositiveIntegerField(blank=True, help_text='Нужен для подсчета опыта работы мастера', null=True, verbose_name='Начало карьеры'),
        ),
    ]
