# Generated by Django 4.2.5 on 2024-02-24 07:29

import apps.users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_master_start_of_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='working_hours',
            field=models.JSONField(default=apps.users.utils.default_working_hours, verbose_name='Рабочие часы'),
        ),
    ]
