# Generated by Django 4.2.5 on 2023-10-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_autopartsreview_masterreview_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopartsreview',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='autopartsreview',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='masterreview',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='masterreview',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Оценка'),
        ),
    ]
