# Generated by Django 4.2.5 on 2024-02-18 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_phone_number'),
        ('parts', '0007_alter_autopartscategory_characteristics'),
        ('review', '0008_alter_reviewstatistics_auto_parts_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewstatistics',
            name='auto_parts_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_statistics', to='parts.autoparts'),
        ),
        migrations.AlterField(
            model_name='reviewstatistics',
            name='master_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_statistics', to='users.master'),
        ),
    ]
